name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Check formatting
        run: test -z "$(gofmt -l .)" # test -z means is text lenght 0? // $(...) - command substitution
      - name: Run go vet
        run: go vet ./...
      - name: Run tests
        run: go test ./...
